### ISSUE TITLE
Syntax highlighting stops or skips parts

### ISSUE THREAD

**Issue by ChrisBern** [randy3k/R-Box#102]
Syntax highlighting (R Extended) suddenly stops in the middle of a line (line 1847):

![syntax_1](https://user-images.githubusercontent.com/17614871/27899234-a7bb7670-6229-11e7-981c-1bda00d0c1c2.png)

If I comment line 1847 (btw: the commenting shortcut does only work, if I have the cursor in the first part of the line where the highlighting works), highl. works for a few further lines (until line 1857):

![syntax_2](https://user-images.githubusercontent.com/17614871/27899403-61163ad8-622a-11e7-9501-ba10e6d6d507.png)

If I further comment line 1857, highl. works for the rest of the visible lines (but only half for line 1858):

![syntax_3](https://user-images.githubusercontent.com/17614871/27899529-dbc1c144-622a-11e7-8cd1-cfe18273185e.png)

Seems weird to me :-)

**Comment by randy3k** [comment]
Thank you for the report. It is fixed.

**Comment by ChrisBern** [comment]
Thanks! And a huge thank you for your wonderful work with R-Box/SendREPL!!! (I just see it’s called SendCode now)

Cheers,
Chris
