### ISSUE TITLE
Does not send to R console

### ISSUE THREAD

**Issue by Superstud** [randy3k/R-Box#103]
When I choose syntax "R Extended" then I am no longer able to send to R console. If I change syntax to "R markdown" then source is sent to R console as expected. I have had this problem before but then a work around fixed the problem: opening R-Box settings and saving. This does not work any longer. I use the following key-binding to save and send source:

`[
    { "keys": ["ctrl+b"], "command": "run_multiple_commands", "args": {
            "commands": [
                { "command": "save"},
                { "command": "send_code"
                    "args": {"cmd": "source(\"$file\")"}
                } 
            ]
        }
    }
]`

The file is saved, but the source command is not executed in the R console.

**Comment by randy3k** [comment]
Does it send a the current line using `ctrl+enter`?

**Comment by Superstud** [comment]
No

On Aug 9, 2017, at 13:40, Randy Lai <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it send a the current line using ctrl+enter?

**Comment by Superstud** [comment]
To expand on my answer (I was in a meeting): neither 'Send current line/selection ' nor 'Source current file' works from the menu either.


It seems that it does not see R console at all when 'R Extended' is chosen as syntax. My workaround solved the problem when it occurred (sometimes several times a day) before.


Arne


________________________________

**Comment by randy3k** [comment]
I wonder if there are any error messages in the console. You should choose R as your default program.

**Comment by Superstud** [comment]
Console error message:

"ConEmuC.exe not found. Specify the path to ConEmuC.exe in SendCode.sublime-settings."

**Comment by randy3k** [comment]
If you want to send code to R GUI, you should run `SendCode: Choose Program` to select R GUI.

**Comment by Superstud** [comment]
Thanks, that worked. I do not know why it suddenly changed though.
