### ISSUE TITLE
R-Box setting for windows

### ISSUE THREAD

**Issue by wdkang** [randy3k/R-Box#104]
Hi Randy,

I am having trouble setting up R-Box to work on my windows computer. In particular, I am not sure how to configure rscript_binary and additional_paths. It would be much appreciated if you could provide some examples to follow.

Thanks

**Comment by randy3k** [comment]
In most cases, R-Box will be able to find `Rscript.exe` automatically. The settings `rscript_binary` and `additional_paths` are only needed if it cannot be found automatically. Is something not working for you?

**Comment by wdkang** [comment]
In my case, the path for Rscript.exe was not automatically found after I installed R-box. Should I uninstall and reinstall it to see if it makes a difference?

**Comment by randy3k** [comment]
Then you might need to locate it under `C:\Program Files` and set the variable `rscript_binary`.

**Comment by wdkang** [comment]
Now I have the following for R-Box and did not receive any error message.
{
    // enable auto completions
    "auto_completions": true,

    // show popup hints
    "show_popup_hints": true,

    // path to Rscript, for example
    // (mac, linux): "/usr/local/bin/Rscript"
    "rscript_binary": "C:\\Program Files\\R\\R-3.4.1\\bin\\x64\\Rscript.exe",

    // additional paths to PATH variable
    "additional_paths": []
}
   
If I want to send R code to R console, how should I configure sendcode? 
I used     "r" : {
        "prog": "R GUI"
    }
However, the error message says r gui is not supported for the current syntax. My syntax is set as R extended.

Any idea?

**Comment by randy3k** [comment]
You should use the command `Send Code: Choose Program` and select "R GUI".

**Comment by randy3k** [comment]
Btw, you need to also install `Send Code`.

**Comment by wdkang** [comment]
It is working now. Thank you so much for the quick response and patience!
