### ISSUE TITLE
'toggle comment' only gives markdown comment, not R comment 

### ISSUE THREAD

**Issue by katelie** [randy3k/R-Box#105]
I noticed yesterday that while writing R Markdown documents that 'toggle comment' does not work as expected - in both R chunks and Markdown regions it gives a markdown style comment '\' , rather than the R '#' comment indicator.  I believe that this was working previously (within the past week?) in R Markdown documents. Is there any way to fix this to give the appropriate comment type based on context (# in {r} chunks, \<!-- in md regions) ?

**Comment by randy3k** [comment]
Thanks for the report. It is fixed in v3.4.11.
