### ISSUE TITLE
Request: When render display messages in terminal

### ISSUE THREAD

**Issue by dacarras** [randy3k/R-Box#106]
Hi randy3k,

R-box used to render R-markdown files, from the r-box menu and display its building process in the terminal of choice, r console for example. As of today, when r-markdown files are rendered, the building messages are now display within the sublime console.

![](https://www.dropbox.com/s/9gadbjqm5s2b8gx/Screenshot%202017-08-26%2022.37.21.png?raw=1)

Is it possible to switch it back? or to have the choice of where to display those messages (within sublime, or terminal)?

I guess this changes where introduced to correct the R-box menu, to render only matching files to their extension (rmd for r-markdown, rnw for sweave, knit rnw to pdf).

In any case, thanks for this package randy3k!
Diego.

**Comment by randy3k** [comment]
@dacarras Thanks for being interested in R-Box. You are correctly that they are updated so that the files will always be rendered in Sublime Text which is also a more "Sublime" way of doing stuffs. If you really miss the old way of sending the command, you could either define a `send_code` keybind in `Default (platform).sublime-keymap`,
```
[
    {
        "keys": ["ctrl+shift+r"], "command": "send_code",
        "args": {"cmd": "rmarkdown::render('$file', encoding = 'UTF-8')"},
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.r" }
        ]
    }
]
```

or define it in `Main.sublime-menu` like

```
[
    {
        "caption": "SendCode",
        "id": "SendCode",
        "children": [
            {
                "command": "send_code", 
                "args": {"cmd": "rmarkdown::render('$file', encoding = 'UTF-8')"}
            }
        ]
    }
]

```

**Comment by dacarras** [comment]
Many thanks @randy3k it works like a charm!

**Comment by randy3k** [comment]
@dacarras 

Given it more tests, the new implemented does not seem to be very satisfactory. I have decided to revert back to the old way of sending code to whatever. 

v3.5.4 will be just like it used to be.
