### ISSUE TITLE
R-Box/SendCode Stopped Working

### ISSUE THREAD

**Issue by pjc42** [randy3k/R-Box#108]
I am sure that this is user error but can't figure out what SendCode is doing.

R-Box/SendCode was working brilliantly yesterday but today "suddenly" appears to have stopped working for everything except RGui. Yesterday, with no change that I can recall, it was sending great to R console running in ConEmu. I simply set SendCode to send to ConEmu, ran R in the console and R-Box/SendCode seemed to pick it up fine. 

Windows x64 env with latest sublime and R.

Have uninstalled/reinstalled R-Box and SendCode, Trying to get to work in RTerm inside ConEmu. This was all working perfectly as of yesterday even. I don't know what I would have changed. 

Apologies for the obviously bad question.

**Comment by randy3k** [comment]
Are there any error messages in the Sublime Text console? I also don't have much idea...

If it is sending to RGUI, it means SendCode is working. It may be an issue of ConEmu.

**Comment by pjc42** [comment]
Yes, sorry dug deeper. SendCode required me to add path to conemuc in .sublime-settings. After adding:

` "conemuc" : "B:/bin/ConEmu/ConEmu/ConEmuC64.exe" `

SendCode started working fine again. This definitely wasn't in there yesterday so odd that it worked then.

**Comment by pjc42** [comment]
Thank you for terrific plugin and terrific support.
Have tried rice but getting occasional python error messages mid stream R processing. Is rice more of a WIP?

**Comment by pjc42** [comment]
a really nice to have for working with .Rmd files would be functions to select (and execute):

- current code chunk, everything between current ```{r} ``` marks
- all code chunks above current chunk, super useful for restarting R and getting caught up to where you currently are
- all code chunks, just execute the file

Would have a go myself but the learning curve on these plugins looks pretty large. Any ideas where I might find something like this? Or would you consider adding to nice to have list for R-Box?

regardless, appreciate your work, thank you for sharing

**Comment by randy3k** [comment]
Hi pic42, I would consider rice is ready to use, what error did you get exactly? It may be a bug.

**Comment by randy3k** [comment]
I was informed that `rice` may not be working with python 2.7 on Windows. It may be the reason if you were using python 2.7.

**Comment by pjc42** [comment]
I'll open the issue in rice with an example of what I am seeing. I'm using python 3.6.

**Comment by randy3k** [comment]
Thanks. Any feedback would be valuable.
