### ISSUE TITLE
r-box color schemes issues

### ISSUE THREAD

**Issue by faridcher** [randy3k/R-Box#113]
Here are quite a few issues with rbox syntax (color schemes): 

- rbox doesn't grey out the comment lines in rnw files

![r-box sweave](https://user-images.githubusercontent.com/9982519/30749210-92368690-9fbf-11e7-9f64-8bdf65f489ce.png)

![sublime Latex syntax](https://user-images.githubusercontent.com/9982519/30749336-ea05f8d8-9fbf-11e7-9980-84f0e4c00154.png)

- the contrast of code chucks is very low (with regard to what is available in rstudio) (also the case with rmarkdown and rmd files)
![rstudio rnw code chunks](https://user-images.githubusercontent.com/9982519/30749887-a9be65f6-9fc1-11e7-9c6d-6bea5a923554.png)

![r-box code chunks](https://user-images.githubusercontent.com/9982519/30749915-c24c0a9c-9fc1-11e7-86c3-815a14c9310b.png)

- r script comment coloring doesn't always work (when there is a comma at the end of the line; maybe update the regular expression!)
![image](https://user-images.githubusercontent.com/9982519/30750434-62bb9c94-9fc3-11e7-90cf-debcfc5408a4.png)

For now I switch to normal sublime text syntax.

**Comment by randy3k** [comment]
1. fixed f3a001b
2. a8d8e35 added a scope `markup.raw.code-fence.latex.rsweave`, it will depend on your color scheme to highlight the code block. For instance, `Mariana` highlight the block.

![screen shot 2017-09-22 at 12 49 27 pm](https://user-images.githubusercontent.com/1690993/30755412-7c9775ae-9f94-11e7-9fc7-c65cb2df58ab.png)

3. fixed 6d5b02e

**Comment by faridcher** [comment]
Great job @randy3k! All issues are resolved.

**Comment by faridcher** [comment]
It seems I am a good bug finder and you are a perfect bug hunter 👍 .
All worked. Great job.

**Comment by randy3k** [comment]
Great. Apparently, you are the only one using the Rnw syntax...
