### ISSUE TITLE
go to symbol for r scripts

### ISSUE THREAD

**Issue by faridcher** [randy3k/R-Box#114]
In rstudio the following pattern in an r script creates a heading in the navigation panel. In sublime, navigating through "Go to symbol" by detecting this pattern is  useful. (pound some text four dashes)
```r
# text ----

# some text ----
```

**Comment by randy3k** [comment]
It is unfortunately not possible to add items to "go to symbol" list. There must be several packages doing similar things, check https://packagecontrol.io/packages/TodoReview for instance.
