### ISSUE TITLE
Pipe (%>%) is treated as LaTeX comment in R Sweave files

### ISSUE THREAD

**Issue by adibender** [randy3k/R-Box#115]
Using the R Sweave Syntax, code is greyed out/treated as Latex comment, when preceded by the pipe `%>%` within r chunks. 

Matter of fact, everything after the first `%` is treated as latex comment.

**Comment by adibender** [comment]
Thx for quick fix. Issue appears to be solved!

**Comment by jacekma** [comment]
I dont see the quick fix in here, I dont get how to use that sublime-syntax.file here, is it relevant? Could some please help me on that? Thanks.
