### ISSUE TITLE
Format Code is capturing text from `.Rprofile` and `.First()` output

### ISSUE THREAD

**Issue by rsaporta** [randy3k/R-Box#116]
Format Code is capturing text from `.Rprofile` and `.First()` output and inserting into the file above the function formatted.

**Comment by randy3k** [comment]
Instead, you should make sure the print statement is only invoked in an interactive environment:

```
if(interactive()){
    # code
}
```

**Comment by rsaporta** [comment]
except needed for log files.   Not a big deal, as long as you are aware

**Comment by randy3k** [comment]
Printing any messages in `.First()` non-interactively will also break many use-cases that need to parse the result from R. If you need to print things for log-files, you may consider using an environment variable to consider the verbosity.

**Comment by rsaporta** [comment]
these are good points.  feel  free to close this issue

**Comment by randy3k** [comment]
awesome.
