### ISSUE TITLE
format code doesn't work on Mac and Ubuntu

### ISSUE THREAD

**Issue by zhifeiyan** [randy3k/R-Box#119]
Format code doesn't work on my Mac and Ubuntu. Other features work as expected. How could I fix this? Some pointer would be very helpful! Thanks!

**Comment by randy3k** [comment]
Are there any error messages in Sublime console?

**Comment by zhifeiyan** [comment]
Hi Randy, i think the reason was that i didn't install formatR package. Thanks for your suggestion!
