### ISSUE TITLE
Error in R Sweave syntax

### ISSUE THREAD

**Issue by adibender** [randy3k/R-Box#120]
As of the new dev version of sublime text, this error message pops up for Rnw files: 

`Error loading syntax file "Packages/R-Box/syntax/R Sweave.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

**Comment by randy3k** [comment]
Thanks for the report. It must be due to the new `embed` feature for the dev channel.

**Comment by randy3k** [comment]
The current master should fix it, though I didn't test it thoroughly.

**Comment by adibender** [comment]
so far appears to work

**Comment by adibender** [comment]
I'll close this, as development has been moved to R-IDE
