### ISSUE TITLE
cannot install R-BOX

### ISSUE THREAD

**Issue by lucien0410** [randy3k/R-Box#124]
I am able to find R-BOX on sublime Package Control: install package. 
However, when I clicked R-BOX, the installation process initiated and stopped immediately.
The same happens when I tried to install SendCode. 
Do you have any idea what goes wrong?

**Comment by randy3k** [comment]
Package control is current down due to a recent update of github. You will need to either install the packages manually or wait for the fix.

**Comment by lucien0410** [comment]
Thank you Randy for the quick response.  Then this is not an issue on your side.
