### ISSUE TITLE
Highlighting function names in default R syntax

### ISSUE THREAD

**Issue by mikedecr** [randy3k/R-Box#127]
Hi there, not exactly sure where to put this.

R-Box provides the `syntax.R` file for modifying the list of known packages (for highlighting function names). Now that R-extended has been merged into the default R syntax, is there a good way to extend the function names recognized by the default R syntax for the same purpose? 

Thanks for all the great work.

**Comment by randy3k** [comment]
In short, the answer is no. However, you should be able to extended the R syntax with `syntax.R`

**Comment by mikedecr** [comment]
Thanks, this worked.
