### ISSUE TITLE
Building sweave documents written in UTF-8 encoding

### ISSUE THREAD

**Issue by alpha195** [randy3k/R-Box#131]
When I tried to build sweave documents written in UTF-8 encoding, Every character was broken.
I found this problem came from the option in 'R sweave.sublime-build' 
(Using PackageResourceViewer)
```json
    "variants": [
        {
            "name": "knitr",
            "cmd": [
                "Rscript", "-e",
                "knitr::knit('$file_name'); tools::texi2dvi('$file_base_name.tex', pdf = TRUE)"
            ]
        }
    ],
```

I can solve this problem changing `knitr::knit('$file_name')` to `knitr::knit('$file_name',encoding='UTF-8')`
Can you add option 'building sweave documents written in UTF-8 encoding ' in package settings?

**Comment by randy3k** [comment]
I believe it can be solved by setting the `encoding` key of `options`.

**Comment by alpha195** [comment]
There was such a way, it works! Thank you!
