### ISSUE TITLE
support R help files

### ISSUE THREAD

**Issue by maxheld83** [randy3k/R-Box#24]
I'd be nice to have the R help docs show up somewhere in the UI (not just fly by in the terminal or Sublime REPL). Maybe as a new tab ...

https://sublime.wbond.net/packages/SublimePeek-R-help seemed to have tried this, but it's dead.

**Comment by randy3k** [comment]
How R-Box shows a popup window when link to https://www.rdocumentation.org/

**Comment by adibender** [comment]
Great stuff! 
It appears though, that the "Help" link does not appear when function documentation spans 3 Lines or more

**Comment by randy3k** [comment]
Would you tell me one of such functions?

**Comment by adibender** [comment]
sry, might not have to do with docu length, but here is an `termplot` example: 
![termplot](https://cloud.githubusercontent.com/assets/1672665/20980596/7c492d7a-bcb1-11e6-8af8-63c3628f9358.jpg)

Not a priority for me. Could be left as it is as far as I'm concerned.

**Comment by randy3k** [comment]
I will try to address it.

**Comment by randy3k** [comment]
I understand the issue now, the `&` character has to be escaped.

**Comment by randy3k** [comment]
It is fixed in version 3.4.1.
