### ISSUE TITLE
Linux: send to terminal

### ISSUE THREAD

**Issue by kklot** [randy3k/R-Box#26]
I see the options of `tmux` and `screen`, how can I send to R in `gnome-terminal, pantheon-termin,...` instead.
Many thanks!

**Comment by fabeit** [comment]
@randy3k what is "screen" in linux?

**Comment by rsaporta** [comment]
@fabeit   [https://en.wikipedia.org/wiki/GNU_Screen]

**Comment by randy3k** [comment]
[SendText+](https://github.com/randy3k/SendTextPlus) is now capable of sending code to gnome-terminal.
