### ISSUE TITLE
Ctl + enter in Linux does not recognize $, which is used in list object

### ISSUE THREAD

**Issue by melmasri** [randy3k/R-Box#27]
In Linux when using screen.   

When you have a list say "lobj" that has names, say "o1" and "o2", then in R one can call lobj$o1 to see o1. 
However, when executing lobj$o1 in sublime using ctl+enter, only lobj is executed. One has to add a backlash as lobj\$o1 to execute it.

This would be a quick fix :). Thanks

**Comment by randy3k** [comment]
This is funny. Linux and Mac screen behaves differently. When I run `screen -X stuff 'a$b\n'` on my mac, it gives `a$b\n` without executing the command.

But on Ubuntu, I get only an executed `a`.

**Comment by melmasri** [comment]
great. It works
