### ISSUE TITLE
Linux-screen Error "Remote command is too long."

### ISSUE THREAD

**Issue by melmasri** [randy3k/R-Box#28]
Hello, 
When using Sublime-Text 3 with the latest R-Box, under Linux (Debian)-screen, I got "Remote command it too long" error when ever I used C+b on a long function. 

A similar discussion is shown here 
http://stackoverflow.com/questions/25484585/sublimetext-with-screen-remote-command-too-long

However, I compared the parts of your sendtext.py and the SendText.py in the discussion they seem similar. 
Is there a way to solve it. Thanks.

**Comment by randy3k** [comment]
Strangely, I have already include that patch. 

I am not out, will try when I am back home.

**Comment by randy3k** [comment]
I just notice that the fix there was not a valid fix. I am still struggling on the patch. Meanwhile, I recommend you to use tmux. Tmux is better than screen in many senses.

**Comment by randy3k** [comment]
Try it out.

**Comment by melmasri** [comment]
I haven't  used tmux before, now since I tried, yes I find it better in many ways. 

I'll try screen and let you know soon.
