### ISSUE TITLE
dollar sign issue in roxygen for R-extended syntax

### ISSUE THREAD

**Issue by hafen** [randy3k/R-Box#30]
When I put a dollar sign in a code example in roxygen using R-extended syntax it fouls up the syntax highlighting of the rest of the document.  I can escape the dollar sign but then my package check fails.  I'd take a crack at fixing it if I understood tmLanguage files.

**Comment by randy3k** [comment]
You are appreciated if you can provide an example.

**Comment by hafen** [comment]
Oh yeah, sorry.

Here's a simple example:

```
#' My function
#' 
#' @param x data
#' 
#' @example
#' myFunction(iris$Sepal.Length)
myFunction <- function(x)
  x
```

Everything after the dollar sign (the rest of the source code in the file after the roxygen block) is not highlighted correctly anymore.

**Comment by randy3k** [comment]
It seems hard to activate latex without some works. For the moment, I will just disable latex syntax.

**Comment by randy3k** [comment]
I have release a partial fix, which essentially disable latex syntax. There are two things to complete in the further

1. latex support in some of the fields
2. support R code in `@examples` field.

**Comment by hafen** [comment]
Thanks!  I'll try it out.
