### ISSUE TITLE
Option to modify the path when sourcing a file or setting working directory

### ISSUE THREAD

**Issue by ankur-gupta** [randy3k/R-Box#32]
I have been using this package (and its predecessor) for about an year now and I love it. 

I had a situation in which I was running ST3 on my MacOS but my terminal was running Ubuntu via virtual machine. The virtual machine folders were mounted on the MacOS at this location: `/Users/<username>/vm/`. Most common reason for such a workflow is because you want to develop on the same OS as production. 

Anyways, this meant that I had to modify the path sent from ST3 via R-Box in the following manner:
`/Users/<username>/vm/path/to/file.R` to `/home/ubuntu/path/to/file.R`. As an example, instead of sending `setwd("/Users/<username>/vm/path/to/file.R")` to the terminal, I needed to send this to the terminal: `setwd("/home/ubuntu/path/to/file.R")`. 

I did this by modifying the file `sendtext.py` and the user settings and then re-packaging the R-Box package and using it. This worked great until ST3 updated R-Box automatically and I lost my changes. So, I decided to fork this repository and then make these changes. I have tested the changes on ST3 and everything works nicely. The changes are only a few lines.

Here is the change: https://github.com/ankur-gupta/R-Box/commit/9d87ec117e4df83fd37c72f73be299231de06124

Now, I am not sure if this is something a lot of people would want to have. If there is demand or utility for this, **I'd like to send you a pull request**. This way I won't have to keep on merging your changes into mine every so often. 

Let me know what you think, @randy3k.

**Comment by randy3k** [comment]
it seems too much customization for me...

**Comment by ankur-gupta** [comment]
That's fine. I'll maintain a fork.
