### ISSUE TITLE
Error when wanting to open Rgui

### ISSUE THREAD

**Issue by JanaJarecki** [randy3k/R-Box#33]
When I try to open the external R window (e.g, press Ctrl+Enter) Rgui does not open and the following error message appears: http://imgur.com/wTcvLUm. It worked until Friday.

INFO
I am on Windows 7, 64 Bit, R-Box v2.3.1

I do set the path to R manually in the Package settings - R-Box - Settings User via

   {
      // path to Rgui.exe (for windows only)
      "R64": "C:\\Programme\\R\\R-3.1.2\\bin\\x64\\Rgui.exe",
   }
(using double backslashes)

**Comment by randy3k** [comment]
should be fixed in 8a39e5e7cae10b10d13b8870451e86e42ae6c478

**Comment by JanaJarecki** [comment]
Yes! Thanks. :)

**Comment by randy3k** [comment]
Sorry for the bug. :)
