### ISSUE TITLE
Sweave Build File is more like knitr tex?

### ISSUE THREAD

**Issue by jakob-r** [randy3k/R-Box#35]
If we want to Sweave - why doesn't the build file looks like this
```
{
    "selector": "text.tex.latex.rsweave",
    "working_dir": "${project_path:${folder}}",
    "cmd": [ "R CMD Sweave $file --encoding=UTF-8" ],
    "shell": true
}
```
Calling knitr leads to some issues using *sweave only* related commands, if one uses real Sweave.

**Comment by randy3k** [comment]
I think it is a matter of taste. You can always define your own sublime-build commands.

**Comment by randy3k** [comment]
I have added a variant build for Sweave.
