### ISSUE TITLE
better support RMarkdown syntax

### ISSUE THREAD

**Issue by maxheld83** [randy3k/R-Box#36]
I love writing RMarkdown with R-Box in ST3, but it seems I can't get proper syntax highlighting and REPL-ing/Build System to work at the same time.

If I select `AcademicMarkdown` as a syntax, highlighting for *italics* and even @citations works fine, but no REPL or Build system or R highlighting.

Conversely, If I choose R Markdown, the above works fine, but I loose syntax highlighting for *italics* and other simple Markdown stuff.

What's up with that? My screw-up, or still a limitation?

Ps.: fantastic work! – It's like magic to have R in your ST3. No more IDEs.

**Comment by randy3k** [comment]
RMarkdown is derived from [Markdown Extended](https://github.com/jonschlinkert/sublime-markdown-extended) and obviously it doesn't support italics and citations.

I will give it a thought. It shouldn't too difficult to add `AcademicMarkdown` support.

**Comment by maxheld83** [comment]
Thanks @randy3k – sorry if I was being dense.
`AcademicMarkdown` support would be super.
Thanks for the great work, can't get over how great it is to have R in ST3.

**Comment by randy3k** [comment]
I have added `AcademicMarkdown` support for sending commands. However, the R code high light will not work as it should be handled by `AcademicMarkdown` syntax.
