### ISSUE TITLE
Highlighting multiple lines causes ST2 to crash

### ISSUE THREAD

**Issue by jmwerner** [randy3k/R-Box#38]
Hi Randy,

When I highlight multiple lines of any R script in ST2 the application crashes. When I uninstall R-Box it does not freeze when I highlight text inside of R scripts. ST2 does not freeze when I highlight text inside of other types of scripts. 

OS X 10.10.2, fresh installs of ST2 and R-Box as of this evening.

Thanks for the help!

**Comment by randy3k** [comment]
Should be fixed by 0d7f943.
2.4.1 is released, it may take a while for package control to update the cache.

**Comment by randy3k** [comment]
Jeremy,

I highly recommend you to use ST 3. Though it is still in beta, it is quite stable and a lot of cool packages are only available for ST3.

**Comment by jmwerner** [comment]
I've been meaning to upgrade for awhile and haven't got around to it, but will soon! 

That new release fixed the problem as well. Thanks!
