### ISSUE TITLE
send selection to terminal and R console

### ISSUE THREAD

**Issue by md2999** [randy3k/R-Box#39]
As far as I can tell R-Box either sends code to the R console OR Terminal OR iTerm. Is it possible to assign three different key bindings to those three options (in order to be able to switch between them)?

**Comment by randy3k** [comment]
It is not possible now. I will consider it.

**Comment by randy3k** [comment]
it is now possible with [SendText+](https://github.com/randy3k/SendTextPlus). For example,
 
```
    {
        "keys": ["super+enter"], "command": "send_text_plus",
        "args": {"prog": Terminal"},
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.r" }
        ]
    },
```
