### ISSUE TITLE
Autocomplete not seeing period-separated words

### ISSUE THREAD

**Issue by rsaporta** [randy3k/R-Box#41]
In Enhanced-R, ST3 was able to correctly identify period-separated words and autocomplete as expected.   This feature seems to be absent from R-Box.
If this was deliberate, can we set a user option to adjust to old behavior? 

![screen shot 2015-04-19 at 11 04 11 am](https://cloud.githubusercontent.com/assets/1760870/7219924/28d189b2-e684-11e4-9c04-61751c83cf17.png)

**Comment by randy3k** [comment]
should be fixed now.

**Comment by rsaporta** [comment]
Tested and confirmed.  Thanks Randy!
