### ISSUE TITLE
Can not send code with Chinese comment

### ISSUE THREAD

**Issue by BillyRen** [randy3k/R-Box#42]
If there's chinese comment in the code, then it can not be send to rgui.exe.

Is there any solution for this issue?

**Comment by randy3k** [comment]
![screen shot 2015-04-24 at 9 25 17 am](https://cloud.githubusercontent.com/assets/1690993/7323502/e1c1b7c0-ea63-11e4-836d-20690d9b6649.png)

I have no issue.

**Comment by BillyRen** [comment]
I tried to reopen the file with UTF-8, but I still can not send any chinese to rgui.exe.

**Comment by randy3k** [comment]
Not sure why, close by now. We can always reopen it.
