### ISSUE TITLE
R-box suddenly not working

### ISSUE THREAD

**Issue by nickriches** [randy3k/R-Box#48]
Hi

I've been using R-box happily for a long time. But today it's suddenly not working. There's no syntax highlighting, and none of the short-cut keys work. I've removed and re-installed it a number of times.

Settings are as follows;

{
	"R64": "C:\\Program Files\\R\\R-3.1.3\\bin\\x64\\Rgui.exe",
	"auto_advance": true,
	"auto_completions": true,
	"prog": "R64",
	"status_bar_hint": true
}

The path to R is correct. Settings are under Packages/User/...

Thanks

Nick

**Comment by randy3k** [comment]
I have no idea how it is happening...did you disable R-Box accidentally?

**Comment by ankur-gupta** [comment]
Can you make sure that the syntax is set to R Extended and not R?

**Comment by nickriches** [comment]
Fantastic. I have R-box back!

That's so simple! Thanks for the help!

(I'm not sure how the syntax unset itself...)

**Comment by rsaporta** [comment]
I had the same issue (the syntax unsetting itself) after one of the auto-updates.  Not sure if it was ST3 or Rbox.  It only occurred on files that were open or in cache.  Closing and re-opening the files resolved it for me.
