### ISSUE TITLE
R's Style Guide

### ISSUE THREAD

**Issue by TrigonaMinima** [randy3k/R-Box#49]
It'd be good to have a feature to autoformat the R code according to the style guidelines like this one [here](https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml)

This feature will be like this plugin of the Python - [here](https://github.com/wistful/SublimeAutoPEP8)

Will it be feasible to have this feature here in this plugin?

**Comment by randy3k** [comment]
You should install https://github.com/jimhester/SublimeLinter-contrib-lintr and follow the instruction [here](https://github.com/randy3k/R-Box#sublimelinter-settings).
