### ISSUE TITLE
ConEmu Configuration

### ISSUE THREAD

**Issue by hathawayj** [randy3k/R-Box#50]
ConEmu is built on cmder foundations I think.  It would be nice if there was a send to ConEmu option on windows.

**Comment by randy3k** [comment]
I think it is the other way round - Cmder is based on ConEmu. However, support should not be very difficult (any PR will be welcomed).

**Comment by hathawayj** [comment]
I wish I was smart enough to know what PR meant in this context and how to make the change myself.  Unfortunately, I am deficient in both...

**Comment by randy3k** [comment]
PR means "push request".  You can clone this repo and add support of ConEmu by modifying `Cmder.ahk` or `Cygwin.ah`.

**Comment by randy3k** [comment]
Conemu is support, see [SendREPL](https://github.com/randy3k/SendREPL).
