### ISSUE TITLE
R-box in OSX Maverics, Sublime 3 not working

### ISSUE THREAD

**Issue by elisafilevich** [randy3k/R-Box#51]
Hi, 
I hope the issues are a good place to post this. 
I installed R-box via package control without problems, but it's not running on my system (I have Maverics and Sublime 3). I checked and the User settings include "prog": "R".  
I had REPL installed, I tried removing it but it didn't help. 
Both R.app and Sublime Text.app are in the same /Applications folder. 

I get no error message so I can't give any more information, it's just that hitting cmd+Enter doesn't open R or send any commands to it if R is open. It just inserts a new line in my sublime file. 

Thanks

**Comment by rsaporta** [comment]
Close ST3, then reopen it.  Then check that at the bottom right of the window it says `R Extended`.

If not, you need to set the Syntax on the file: 

   ` cmd+shift+P`
   `Set Syntax: R Extended`

**Comment by elisafilevich** [comment]
worked! so simple! thanks.
