### ISSUE TITLE
Error in running packages.R

### ISSUE THREAD

**Issue by ankur-gupta** [randy3k/R-Box#52]
```
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
Calls: cat -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'packages/base.json': No such file or directory
Execution halted
```

This failure happens because `packages` is not yet created. We can either add a line to the `packages.R` script to create the folder or change the instructions in the README.md to ask the users to create the `packages` folder themselves.

**Comment by randy3k** [comment]
You are right, stupid me.
