### ISSUE TITLE
set working directory automatically

### ISSUE THREAD

**Issue by smartinsightsfromdata** [randy3k/R-Box#54]
When I use SublimeREPL: R ("driven" by R-BOX of course), I manage to tell it to use the current folder as home folder.  It saves a lot of confusion. The setting is `"cwd": "$folder",`.

Sadly I haven't found how to do the same in RBox when using the R app (I'm using OS X).

Is it possible, and if yes, how?

**Comment by hafen** [comment]
This is something I've wanted as well.  I have a fork that does something like this.  It sets the working directory to the project directory every time you send a command.

https://github.com/hafen/R-Box

You can see the relevant changes in rbox/send_text.py at the bottom of here:

https://github.com/randy3k/R-Box/compare/master...hafen:master

The way you activate it is to set a project variable "R_box_setwd" to true.  So your x.sublime-project file might look something like this:

```
{
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "."
		}
	],
  "settings":
  {
     "R_box_setwd": true
  }
}
```

This is pretty unobtrusive but I haven't gotten around to doing a PR for it.

**Comment by rsaporta** [comment]
Not sure if I follow, but is what you are looking for different than `CMD+\`  ?

**Comment by smartinsightsfromdata** [comment]
First create a project in Sublime Text in a folder foo.
Open a file, as R extended (even without saving the file).

In REPL R, thanks to the setting that I mentioned above, by default the current working directory (cdw) is set to the level of the folder foo. 
It makes Sublime Text work with projects in the same way as Studio does (the setting of wd is totally transparent to the user and I can refer to any subfolder with indirect addressing, e.g.  `./data/somefile.csv`)

@hafen code (that I confess I haven't tried yet but is on my todo list!) should be doing something similar for R terminal (i.e. when we send the code to the R UI): automagically the wd is set to the folder level.

I have never used `CMD+\` but it seems to be trying to save a file?

**Comment by dschneiderch** [comment]
@smartinsightsfromdata 
where did you add that pref? and at what point does it change directory? when ou open a project?
I modified my R-box user setting to:
{
	"prog": "SublimeREPL",
	"cwd": "$folder",
}
i'm not getting anything different.

The problem with CMD+\ is it uses the source files directory.  I usually keep my project-template file in projectdir, in the below structure. in fact, is there a way to turn it off because I hit \ accidentally all the time.
projectdir/
   src/
   data/

**Comment by randy3k** [comment]
Sending code feature is exported to [SendREPL](https://github.com/randy3k/SendREPL).
Please open an issue there on your will.
