### ISSUE TITLE
Autocomplete works strange

### ISSUE THREAD

**Issue by divenyijanos** [randy3k/R-Box#55]
Sublime autocomplete works somewhat strange (I am only guessing this is due to R-Box). First it only suggests built-in functions...
![autocomplete1](https://cloud.githubusercontent.com/assets/7870632/10134581/32d845ee-65e7-11e5-88ed-80801a204f00.png)

... and offers my object when there is no other possibility left.
![autocomplete2](https://cloud.githubusercontent.com/assets/7870632/10134601/555f1b1a-65e7-11e5-9a41-0a4f2ccf90d6.png)

**Comment by randy3k** [comment]
I don't encounter this. Could you try to upgrade to the latest R-Box?

**Comment by divenyijanos** [comment]
I already have R-Box 2.6.6.
Interestingly, if I hit `alt`+`/` I got a different list of suggestions which work great. I do not really understand why the automatic pop-up list is different.

**Comment by randy3k** [comment]
Could you make sure that you are using `R Extended` syntax? I could reproduce it if `R` instead of `R Extended` is used.

**Comment by divenyijanos** [comment]
@randy3k Thanks a lot, it was indeed the problem.
