### ISSUE TITLE
Build with R markdown (.Rmd)

### ISSUE THREAD

**Issue by hungmtuci** [randy3k/R-Box#56]
I use **Sublime text 3** in **Mac OS 10.11** with **R 3.2.2** and **R-Box 2.6.6**

I write markdown in `.Rmd` file with r code 

I selected `Build system` is `R Markdown`
![build system](https://dl.dropboxusercontent.com/u/9118373/Screen%20Shot%202015-10-04%20at%2012.24.48.jpg)

When I run `Build` (`cmd+B`), this error appears  
![error](https://dl.dropboxusercontent.com/u/9118373/Screen%20Shot%202015-10-04%20at%2012.25.46.jpg)

I check the command in console 
![command](https://dl.dropboxusercontent.com/u/9118373/Screen%20Shot%202015-10-04%20at%2012.24.27.jpg)

If I run the same command in terminal, it works and gives the out file `.md`

Can you figure out what was happen here, please? 
![terminal](https://dl.dropboxusercontent.com/u/9118373/Screen%20Shot%202015-10-04%20at%2012.38.20.jpg)

**Comment by jvcasill** [comment]
I currently have the same issue. When I ran a system check using LaTeXing it showed the Rscript was missing. I reinstalled the latest version of R and the system check now finds Rscript, but I still get the same error that @hungmtuci mentions above.

**Comment by hungmtuci** [comment]
I found one temporary solution to display the figure in `.md` file. 

If you run the command `knit()` in `terminal` by copying from the `Sublime console`. The `figure folder` will be created in `~\user`.

Fortunately, if you open `R`
1. run `setwd("\folder containing file .Rmd")`
2. run `knit("file.Rmd"`

The `figure folder` and `file.md` are both generated in `\folder containing file .Rmd`. Now you can open `file.md` with figures.

The advantage when you run `knit()` in `R` or in `terminal`. It will stop if the chunk has error, the errors will be appeared in the result. But if you run through the Rstudio or by other command, file building will be stopped immediately when the chunks get issue.

Hope someone can fix this, and just simple run direct from sublime

**Comment by jvcasill** [comment]
Just to add a bit more, I've been told elsewhere to add ```/usr/local/bin``` to my path in ```~/.bash_profile```, but this did nothing for me.

**Comment by cnjr2** [comment]
I have exactly the same setup as @hungmtuci: `I use Sublime text 3 in Mac OS 10.11 with R 3.2.2 and R-Box 2.6.6` and get the same error.

**Comment by randy3k** [comment]
It is because the PATH variable is handled differently in MAC OS applications. A possible fix is
by https://github.com/int3h/SublimeFixMacPath
