### ISSUE TITLE
Cannot send commands

### ISSUE THREAD

**Issue by mikedecr** [randy3k/R-Box#59]
Hi. Been using R-Box for a while; love it. Suddenly commands aren't sending to the R GUI (3.2.2).  

Getting this message in the console when starting up Sublime: 

`File "rbox in /Users/[my_username]/Library/Application Support/Sublime Text 3/Installed Packages/R-Box.sublime-package", line 12, in <module>
ImportError: cannot import name RSendSelectCommand`

R Extended syntax highlighting still works. Tried reinstalling R-Box and disabling the default R package, but neither of those seem to work. Running OSX El Capitan, using most recent Sublime 3 build. Any advice? Thanks.

**Comment by randy3k** [comment]
Sorry about it, fixed now. Try reinstalling R-Box.
