### ISSUE TITLE
R does not open and cannot send commands since Nov-7-15

### ISSUE THREAD

**Issue by JanaJarecki** [randy3k/R-Box#61]
Hi,
I've been working with R-box, Sublime Text 3 (Build 3083), on a Win 7 machine, 64 bit, for a year now, and it worked flawlessly. Since yesterday I cannot paste commands anymore. Neither Ctrl+Enter works nor my user-defined commands, and the R window does not even open anymore.

The console shows nothing after I press, e.g. Ctrl+Enter.
I've tried re-installing r-box, but the issue persists.
The syntax is set to R-Extended.

Any ideas?

**Comment by randy3k** [comment]
There was a bug in last update, but it should be fixed....

Are there any error messages in the console?

**Comment by JanaJarecki** [comment]
Hi!
i have updated the all packages and still nothing happens after Ctrl+Enter.
The console is totally silent unfortunately.

This is the console log
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/JBJ/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/JBJ/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/JBJ/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.434371
startup time: 0.623371
first paint time: 0.626371
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin R-Box.bootstrap
plugins loaded
Package Control: No updated packages

**Comment by randy3k** [comment]
It is strange. The package is loaded. Does the cursor move when ctrl-enter is triggered? Could you make sure that "R" is chosen in "R-Box: Choose Program"? I guess it is the reason.

**Comment by JanaJarecki** [comment]
Yes, that's it. R was not chosen.
The interesting sidenote is that this was one of the solutions I tried this morning.

Thanks a bunch!
Best
Jana

**Comment by randy3k** [comment]
Problem solved, close case.
