### ISSUE TITLE
Auto-advance behavior

### ISSUE THREAD

**Issue by mikedecr** [randy3k/R-Box#63]
This package used to auto-advance only one line when sending a command to the console (or at least it did for me). Recently it began auto-advancing to the next line in the source file *that has text*, not simply the next line. If I prefer the old behavior, how might I switch it back? Been digging for a way to make this happen, but I'm not a python person, so I am a bit lost. Thanks.

**Comment by randy3k** [comment]
Ya, I have reverted it to the old behavior. The settings `auto_advance_non_empty` now controls this behavior. v.2.9.1 will be available via Package control in a while.
