### ISSUE TITLE
Error when wanting to open Rgui (since today)

### ISSUE THREAD

**Issue by JanaJarecki** [randy3k/R-Box#64]
Hi,
an old error re-occurred since yesterday:

When I try to open the external R window (e.g, press Ctrl+Enter) Rgui does not open and the following error message appears: https://www.dropbox.com/s/dbcokixiqwxrepg/Clipboard01.jpg?dl=0

INFO
I am on
Windows 7
64 Bit
R-Box v2.9.1

I have set the path to R manually in the Package settings - R-Box - Settings User via
{
	"R64": "C:\\Program Files\\R\\R-3.1.2\\bin\\x64\\Rgui.exe",
	"prog": "R64"
}

The fix may be analogous to fix number 8a39e5e.

Thanks, best
Jana

**Comment by randy3k** [comment]
Sorry about this. Fixed now.

**Comment by randy3k** [comment]
923e04eaa9f21b54e2047a738892cdb41c87663f
