### ISSUE TITLE
Problem with executing code via SublimeREPL on (L)Ubuntu

### ISSUE THREAD

**Issue by hstojic** [randy3k/R-Box#66]
Hi,

in the last 10 days or so sending R code to SublimeREPL behaves strangely. First, CPU usage goes through the roof, even for simple variable assignments, no real computation involved, the more lines have to be executed the longer it takes. Second, sublime freezes throughout that computation, even if CPU is not at max. Third, this doesn't occur if I use screen or tmux. Finally, if I don't use R-Box, sublimeREPL seems to work without such issues. Anybody else with similar problems?

I'm using Lubuntu 14.04, R version 3.2.2 and Sublime text 3 version 3083.  I would gladly provide more details if you tell me which ones.

Best,
Hrvoje

**Comment by randy3k** [comment]
I don't experience high cpu usage on MacOSX. It is strange since you mentioned that sublimeREPL works by itself.

**Comment by hstojic** [comment]
Ok, suddenly there are no problems anymore, now it executes fine again, although I didn't do anything about it. Probably some of the updates resolved the issue.
