### ISSUE TITLE
auto advance not working?

### ISSUE THREAD

**Issue by yueatwork** [randy3k/R-Box#67]
I noticed that send_text.py has just been updated. 

Now if I set auto_advance to true and hit Ctrl-Enter in sublime, I lost my mouse entirely. I need to manually click the sublime editor to reactive my mouse.  In the end I just decided to turn off auto_advance.

**Comment by randy3k** [comment]
It has been fixed in the last commit. It will take some time for Package Control to load the changes.

**Comment by yueatwork** [comment]
thank you sir, great package

**Comment by randy3k** [comment]
It is available in Package Control now. You should be able to enjoy the updated R-Box. :)
