### ISSUE TITLE
Something wrong with the copy & paste code into terminal?

### ISSUE THREAD

**Issue by yueatwork** [randy3k/R-Box#69]
I was using R-box yesterday (2016-01-27) and from time to time the copy & paste in r-box fails to work.

It is really hard to replicate the bug as it depends on the way I wrote my code, (the name of the function, length of a line, etc.) Some of my code is proprietary that I cannot disclose on a public forum. So I will just try to describe the issue as accurate as I can. 

I have only seen this issue in linux, haven't tested it in windows.

What I did is trying to execute a block of code enclosed with { ... }, usually I do something as the following:

```
{   # hit ctrl + Enter here
    ... code ...   # these code automatically gets copied to a terminal
}   # end of the block
```

Yesterday when I tried to execute a block like below:

```
{
    ... some code ....
    variable <- some_long_function_name_with_underscores(arg1, arg2, arg3)
    ... some code ....
}
```

The following gets pasted into the terminal

```
{
    ... some code ....
    variable <
```

It happened multiple times with different scripts, Changing the function name fixes the issue (but the new function name doesn't have to be short either)  

I am not sure what's going on but would be happy to provide more details.

**Comment by randy3k** [comment]
It is odd.

1. What program were you using? tmux or screen? 
2. Does the cursor move to the end of the block after hitting enter?
3. Does it always end with an arrow `<`?

**Comment by yueatwork** [comment]
1. I use tmux (built from source) in CentOS 7
2. Yes, the cursor move to the end of the block but the block is only partially copied to the terminal
3. Yes, it always ends with <

**Comment by gwd999** [comment]
I am using Sublime 2.0.2 Build 2221 on windows 7 Enterprise Service Pack 1 with latest R-Box package and R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk" (64-bit). 
I am also having similar issues. Hitting Ctrl-Enter on the first line of my SomeCode.R file starts up the R GUI Console and sends this (first) code line to the GUI-console. But from there on nothing else gets transferred anymore. 
Another behaviour noticed - when reaching the start of a function definition the cursor jumps to the end of the definition but again nothing gets transferred.

**Comment by randy3k** [comment]
The send code functionality has been exported to [SendREPL](https://github.com/randy3k/SendREPL).
