### ISSUE TITLE
Syntax highlighting bug with function calls as arguments

### ISSUE THREAD

**Issue by DexGroves** [randy3k/R-Box#72]
Seems that any builtin function that gets its own highlight colour starts to break when function calls get passed as arguments.

I only started noticing this after updating to the new Sublime 3 build this morning, so I would assume it's recent. An old version of ST3 (and R-Box) has the correct highlighting.

This looks fine, with `x` and `y` tinted to show that they are argument names.
```R
data.frame(x = a, y = b)
```

But typing the following in R-Extended gives a y without any tint.
```R
data.frame(x = f(a), y = b)
```

Thanks for your work on this awesome plugin!

**Comment by randy3k** [comment]
I believe it is a bug of Sublime 3103. Sublime 3103 has introduced a new syntax definition format .sublime-syntax which uses yaml. It may be interested in switching to it.

**Comment by randy3k** [comment]
The master branch has updated to the new ".sublime-syntax" format, give it a try.

**Comment by randy3k** [comment]
It should be fixed. Closed for now.

**Comment by DexGroves** [comment]
Thanks!
