### ISSUE TITLE
Can I do complement method is installed anew ?

### ISSUE THREAD

**Issue by yuntas** [randy3k/R-Box#73]
Mr. randy3k,

Thanks for nice packages.

I wanna complement against new packages is installed by "install.package()".

For example, I can complement against the following word, `lm`

``` r
lm [Tab]
↓
# Logistic regression model
modelName <- glm(DV ~ predictor1 +* predictor2, data = df, family = "binomial")
summary(modelName)
```

But, I can't complement new packages, I can only complement method name...

What should I do ?

**Comment by randy3k** [comment]
Would you rephrase your question? I could not get it.

**Comment by yuntas** [comment]
Sorry.

I wanna complement like `plot` or `lm` against new Packages.

for exapmle, 

```{r}
install.packages("dplyr")
db = src_postg [Tab]
↓
db = src_postgres(dbname='',host='',port='',user='',password='')
```

**Comment by randy3k** [comment]
it is supported in a slightly different way in the recent refactoring.
