### ISSUE TITLE
R code is not executed at 'R markdown' syntax

### ISSUE THREAD

**Issue by lovetoken** [randy3k/R-Box#74]
In the current  R code is not executed at 'R markdown' syntax

I am a Korean who favored the R-box package of sublime text. 
I really thank you for providing the packages R-box.
By the way, today I found the problem.
I think recently this issue occurred after sublime text 3 upgrade to the 3130 bulid.

When R markdown syntax situation in the <kbd>cmd</kbd> + <kbd>enter</kbd> code execution for the chunk of code in this does not send to command but paragraph skipped(next line). T_T

**Comment by randy3k** [comment]
3103 introduces a new syntax format and R-Box has switched to the new format. And apparently, I didn't test enough. The version 2.9.8 should fix the issue.

Thanks for the report.

**Comment by lovetoken** [comment]
Code execution problem at R markdown syntax be fixed.
Thank you! :)
