### ISSUE TITLE
Bug in the new R-Box 3.0.4: send current line not working

### ISSUE THREAD

**Issue by Rloveeee** [randy3k/R-Box#76]
Hi,

I just upgraded my R-Box package to 3.0.4 and I cant send anymore lines to my R console.
I was in 2.9.6 version previously.
He asked me to install SendText+ also, I did it but it still not working ?

Did I miss something ?

Thanks,

**Comment by randy3k** [comment]
Did you select the program via `SendText+: Choose Program`? Also, make sure that you installed SendText+ but not SendText.

**Comment by Rloveeee** [comment]
No I didnt, it works now !

Thanks Randy

2016-03-01 12:32 GMT+01:00 Randy Lai <notifications@github.com>:
