### ISSUE TITLE
R-box cann't build r files in linux

### ISSUE THREAD

**Issue by weijy026a** [randy3k/R-Box#79]
I installed the newest sublime text 3 and R version 3.2.3 recently and the R-box in Linux Mint. I can see R-box appears in the menu list. However when I type Ctrl+B or excute "Bulid and reload", the program doesn't have reponse. How can I check the configuration ?

**Comment by randy3k** [comment]
I think yo have misunderstood the page of "Build and reload", it is used to build and reload a R package. To use that, you have to open a termianl/R program first.

May be I should first you this question first, could you send commands to the terminal/R program when you hit "ctrl+enter"?

**Comment by weijy026a** [comment]
I want to run one "*.r" files with "Ctrl +B" I can use this in windows platform but cannot use it in linux platform. I don't know why this happen.

**Comment by randy3k** [comment]
What program are you using on linux? Did you choose that program in `SendText+: Choose Program"?

**Comment by weijy026a** [comment]
Use sublimerepl and it can work now.
