### ISSUE TITLE
Disable suggestions

### ISSUE THREAD

**Issue by striatum** [randy3k/R-Box#80]
Hello! I wonder how can we disable suggestions under Mac OSX? It seems that the "normal" way (Preferences -> Package Settings -> R-Box -> User Preferences: "auto_completions": false, "status_bar_hint": false) does not work. I simply cannot figure out what to do.

Thanks!

**Comment by randy3k** [comment]
Would you explain how it is not working? It works perfectly fine on my computer.

**Comment by striatum** [comment]
Well, window with suggestions always pops up no matter what I put into User Preferences. I started suspecting that some other package is messing the behavior or R-Box. Is that possible? For example, I have related packages (that ask for R-Box) like LaTeXing and knitR.

**Comment by randy3k** [comment]
Is the pop up R-Box related, or generic pop up by sublime text?

**Comment by striatum** [comment]
It appears in R-code snippets when I do Rnw or Rmd project. But it also appears in plain R.

**Comment by randy3k** [comment]
By the way, are you using ST 2 or 3?

**Comment by striatum** [comment]
ST3 (sorry for forgetting to mention!)

**Comment by randy3k** [comment]
It sounds like the default R snippets. They could be disabled by disabling the default R package. It would do no harm to R-Box except the snippets.

**Comment by striatum** [comment]
And how to do that?

**Comment by randy3k** [comment]
In the command palette, search for "Package Control: Disable Package".

**Comment by striatum** [comment]
Thanks!

**Comment by randy3k** [comment]
Can we close it?

**Comment by striatum** [comment]
Sure!
