### ISSUE TITLE
c is not scoped as support.function.r

### ISSUE THREAD

**Issue by MattDMo** [randy3k/R-Box#82]
From looking over your codebase, I'm assuming that `support.function.r` is supposed to be all of the built-in functions. However in, 

``` r
myvar = c(1, 2, 3, 4, 5)
```

(for example), `c` is only scoped as `source.r meta.function-call.r`, whereas for something like

``` r
myvar.vector = as.vector(myvar, mode="numeric")
```

`as.vector` is scoped as `source.r meta.function-call.r support.function.r`.

One other thing - in `syntaxes/R Support Functions.sublime-syntax`, you have these large groups of support functions that I assume are related in some way (I'm only a beginning R programmer). Would it be possible to add a sub-scope like `support.function.XXX.r` where `XXX` is a descriptor of some sort? I'm the maintainer of the [Neon Color Scheme](https://github.com/MattDMo/Neon-color-scheme) and I'm trying to add some more colors to the R/R-Box syntaxes.

**Comment by randy3k** [comment]
it is addressed in the latest refactoring.
