### ISSUE TITLE
constant.language not scoped as function parameter 

### ISSUE THREAD

**Issue by MattDMo** [randy3k/R-Box#84]
![r-box constant language parameter](https://cloud.githubusercontent.com/assets/1776358/16546229/9db1fd8c-4111-11e6-8210-360dd242dbcb.png)
When `TRUE` or other `constant.language.r` members are non-keyword function parameters (`func(TRUE)`), they are  highlighted (incorrectly) like any other function parameter. However, if part of a key-value (`func(option=TRUE)` they are highlighted appropriately.

**Comment by randy3k** [comment]
Thanks for catching this.

**Comment by randy3k** [comment]
This is fixed in the [latex](https://github.com/randy3k/R-Box/tree/latex) branch, however, we need to wait until https://github.com/sublimehq/Packages/pull/370 is merged.

**Comment by randy3k** [comment]
Actually, I was able to split the commits, fixed in 9154d0646706555855097f73a66d71b2c536f70f.
