### ISSUE TITLE
[feature request] Autocomplete all parameters ( args(foo) )

### ISSUE THREAD

**Issue by wilsoncai1992** [randy3k/R-Box#86]
The current autocomplete feature for the function name is cool. And the new `show_hints_on_hover` is wonderful. 

I constantly find myself start typing parameters and cannot revoke hints anymore.

Is there any way we could have autocomplete capability for all function parameters? Similar to the Anaconda package for python? e.g. 
```
"complete_all_parameters": true
```

After all, this is already a wonderful package. Thank you for your great contribution to the data science community!

Best,
Wilson

**Comment by randy3k** [comment]
I am working on a major refactoring, please be patient....

**Comment by wilsoncai1992** [comment]
Wow @randy3k ! This sounds wonderful!

**Comment by wilsoncai1992** [comment]
Thanks for your great work!

**Comment by randy3k** [comment]
I have finally finished the refactoring, will you be able to test the [refactor][1] branch?

[1]: https://github.com/randy3k/R-Box/tree/refactor

**Comment by wilsoncai1992** [comment]
Will test right away! Thanks a lot!

**Comment by wilsoncai1992** [comment]
Works like magic! This is awesome!

**Comment by randy3k** [comment]
It has merged to master. A update will be release in a few days after more testings.

**Comment by wilsoncai1992** [comment]
The new paste method works like charm!
