### ISSUE TITLE
R Sweave Syntax

### ISSUE THREAD

**Issue by adibender** [randy3k/R-Box#88]
Is it by design, that LaTex code is not highlighted in RSweave Syntax?
(sublime 3126, newest R-Box, ubuntu 14.04)

**Comment by randy3k** [comment]
It is fixed in version 0.3.4.

**Comment by adibender** [comment]
thx for the quick fix! However, it appears as if now (after upgrade to 0.3.4.)  LaTeX Syntax is highlighted, 
but R chunks are not. 
This may be related to https://github.com/LaTeXing/LaTeXing/issues/224
Setting the Syntax in sublime to LaTeXing (knitr) produces the same results -> highlighted LaTeX/R-Chunks unrecognized. 
I think the problem is more severe when math syntax is present in the .Rnw file.

**Comment by adibender** [comment]
In fact, it seems only to appear in case math formulas/environments are used.

**Comment by randy3k** [comment]
Would you show me a minimal example?

**Comment by adibender** [comment]
sorry, didn't have to do with math after all. The problem appears when the r-chunks are embedded in 
some environment, for example `itemize` or `enumerate`

            \documentclass{article}
		\begin{document}

		\begin{enumerate}


		<<>>=
		rnorm(1:10)
		@

		\end{enumerate}

		\end{document}

![rchunks](https://cloud.githubusercontent.com/assets/1672665/20981418/f5e32a5c-bcb4-11e6-84b9-975c18894f5a.png)

**Comment by randy3k** [comment]
I think I know what is causing it, let me reopen it.
