### ISSUE TITLE
terminal/iterm problem

### ISSUE THREAD

**Issue by sdaza** [randy3k/R-Box#9]
Hello, 
when I select several lines of syntax and send them from ST to terminal or iterm, I get this type of error: 

> adm2 <- fre
Error: object 'fre' not found

The original line was: 
 
> adm2 <- fread("rawdata/institution/ic2012_data_stata.csv")

In other words, the syntax line is cut. If I select just that line, there is no problem.
Thanks!

**Comment by ankur-gupta** [comment]
I used to be able to send large chunks of data to iTerm until a week ago. But now, large chunks of data come out garbled. Something must've changed recently, not necessarily in R-Box. Maybe iTerm changed?

**Comment by randy3k** [comment]
I confirm it. I think it is a iTerm change. The recent changes of R-Box are specific for Windows platform.
Trying to figure out why.

**Comment by randy3k** [comment]
Could you copy and paste a large chunk of code to the R running in iTerm? Somehow, I am not able to do it correctly now. Can you confirm?

**Comment by ankur-gupta** [comment]
Hey, I did send a huge chunk of R code from ST3 to iTerm and it worked nicely. Thanks a lot.
