### ISSUE TITLE
Diacritics not displayed in when building .Rmd files

### ISSUE THREAD

**Issue by jvcasill** [randy3k/R-Box#91]
I am unable to produce diacritic chars when rendering .Rmd to html using the build function from R-Box. I am running SubimeText build 3126 on Mac OS X 10.12.2. 

    ---
    output: html_document
    ---
    
    # Probando tildes
    
    diacrítico español íéáóú

This is the result.

<img width="1027" alt="captura de pantalla 2017-01-07 a las 09 28 29" src="https://cloud.githubusercontent.com/assets/1747068/21742380/b55fb7f6-d4bb-11e6-8d2b-7aae12992433.png">

If I open the file in RStudio and use the knit button the diacritics show up.

**Comment by jvcasill** [comment]
To add to this issue, I find that if I render the document from the console using...

    rmarkdown::render(input = './diactritics.Rmd', encoding = "UTF-8")

All the diacritics show up. It is only when I use the build function of R-box inside SublimeText that I get NA instead of the desired characters.

**Comment by randy3k** [comment]
I am now in vacation, will look into this next week, thanks for letting me know of it
