### ISSUE TITLE
Split the r-file into cells

### ISSUE THREAD

**Issue by sdaza** [randy3k/R-Box#92]
This may be an useful and interesting enhancement!
See for instance: Stata Improved Editor
Thanks!

**Comment by randy3k** [comment]
would you be more specific?

**Comment by sdaza** [comment]
something like this:

![https://dl.dropboxusercontent.com/u/18116710/Screenshots/predictmen_6.png]]

**Comment by randy3k** [comment]
I see. Perhaps we could use the knitr spin syntax.
https://github.com/yihui/knitr/blob/master/inst/examples/knitr-spin.R

**Comment by sdaza** [comment]
yes!

**Comment by randy3k** [comment]
By the way, this should be addressed in (SendREPL)[https://github.com/randy3k/SendREPL].
