### ISSUE TITLE
Autocompletion for "package::" shows not exported functions after using autocompletion for "package:::"

### ISSUE THREAD

**Issue by mvacha** [randy3k/R-Box#96]
Repro steps:

1.  Request autocompletion for "package::" -> only exported functions show up.
2.  Request autocompletion for "package:::: -> functions from package namespaces environment show up.
3.  Request autocompletion again for "package::" -> both exported and not-exported functions are shown in the autocompletion box.

**Comment by randy3k** [comment]
Did you just press the backspace to change from `:::` to `::`? If it is the case, you have to cancel the menu by pressing <kbd>esc</kbd> and then reactivate the menu by pressing <kbd>tab</kbd>.

**Comment by mvacha** [comment]
You are right, thanks :)
