### ISSUE TITLE
Source File in R-box does not work

### ISSUE THREAD

**Issue by scarygary89** [randy3k/R-Box#97]
Hello, I've been using R-box on Windows for a couple months now and really enjoy sublime/R interface.  However, recently (since the SendCode update), I've been having issues sourcing the R script from sublime to Rgui.  I tried replacing SendCode with the deprecated SendTextPlus -- this fixes the send inline function (Ctrl-Enter) command.  However, all the other functions in R-box still do not interface with Rgui.  Any help is appreciated.

**Comment by randy3k** [comment]
What problem did you encounter when using SemdCode? I think you should fix that issue rather than solving the SendTextPlus issues.

**Comment by scarygary89** [comment]
I experience all the same problems (all functions in R-box) do not interface with Rgui. However, with SendCode, the ctrl-enter command does not work at all.  I am using R version 3.2.2.

**Comment by randy3k** [comment]
Is there any error msg from the sublime console? Please make sure that R GUI is opened first. SendCode has not yet supported opening R GUI automatically.

**Comment by scarygary89** [comment]
I've ran it with the RGUI opened.  Send current line/selection and source file now works only when the R Console is not maximized.  If I maximize the R console window within the R environment, then it will not work properly.  Clear workspace function does not work at all.

**Comment by randy3k** [comment]
Fix in SendCode https://github.com/randy3k/SendCode/commit/035978278b0f59d3dd695cbeb7436d8f7bdf5f04

**Comment by scarygary89** [comment]
Thanks!  That works now.
