### ISSUE TITLE
Autocompletion in comments for some reason

### ISSUE THREAD

**Issue by Bostrolicious** [randy3k/R-Box#98]
I don't know why, but autocompletion does not seem to be properly suppressed in comments. I've noticed that if I uninstall and reinstall R-box, autocompletion won't trigger in comments, but then for some reason it starts up again. It doesn't trigger incorrectly if I change the syntax language to R.

Could this be a bug, or am I just doing something wrong?

EDIT: Autocompletion only appears to trigger at the end of commented lines, not in the middle of them, if that helps.

**Comment by randy3k** [comment]
Thanks for the bug report. It is fixed in v3.4.8.
